# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI 14.x

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install packages & dependencies..
    - run: npm ci
    - name: testing backend unit..
    - run: npm run test
    - name: eslint backend directories..
    - run: npm run lint:backend
    - name: eslint frontend directories..
    - run: npm run lint:frontend
    - name: eslint style directories..
    - run: npm run stylelint
    - name: eslint test backend directories..
    - run: npm run lint:test-backend
