# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI 14.x

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: getong/mariadb-action@v1.1
        with:
          host port: 3306
          container port: 3306
          character set server: 'utf8'
          collation server: 'utf8_general_ci'
          mariadb version: '10.4.10'
          mysql database: 'mogakco_test'
          mysql root password: 'mogatest'
          mysql user: 'mogauser'
          mysql password: 'mogatest'

    env:
      PROJECT_ROOT: '/home/runner/work/mogakco/mogakco'
      NEST: '/home/runner/work/mogakco/mogakco/nest'
      NEXT: '/home/runner/work/mogakco/mogakco/next'
      NODE_ENV: 'development'
