# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI 14.x

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: 패키지 의존성 업데이트..
    - run: npm ci
    - name: 백엔드 유닛 테스트 수행..
    - run: npm run test
    - name: 백엔드 문법 오류 검사 수행..
    - run: npm run lint:backend
    - name: 프런트엔드 문법 오류 검사 수행..
    - run: npm run lint:frontend
    - name: 스타일 문법 오류 검사 수행..
    - run: npm run stylelint
    - name: 백엔드 테스트 문법 오류 검사 수행..
    - run: npm run lint:test-backend
